### ISSUE TITLE
Theory part of the tests

### ISSUE THREAD

**Issue by vohmar** [internetee/accreditation_center#3]
The accreditaion tests consist of two parts - theory and practical. Latter involing tasks that the user has to actually do on test system.

Theory part involves multiple choice questions. Test consists of questions from 3-4 categories about 5 questions in each (15 to 20 questions in total)

https://docs.google.com/document/d/1j8TidOqhfFxS_0WIKhWLtk9ezWR6tLSJth7hmLbWOps/edit?usp=sharing

**Comment by OlegPhenomenon** [comment]
Related #https://github.com/internetee/accreditation_center/pull/60
